# GEC Data Science Program
## Level 1, Lab 1

### Data download

In Lab sessions we use Titanic Data to demonstrate concepts:
https://www.kaggle.com/c/titanic

### Environment Setup

We will be using Anaconda with Python 2.7 (Python 3.6 works too).
https://www.anaconda.com/download/

### Hello world examples

In [2]:
import numpy as np

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.random.rand(10)

array([0.28803618, 0.45624657, 0.67297362, 0.77025079, 0.47429844,
       0.49293948, 0.23190873, 0.83485026, 0.74217046, 0.14382088])

In [6]:
a=np.random.rand(10,3)

In [7]:
a

array([[0.112082  , 0.72959646, 0.82588792],
       [0.94624374, 0.25489925, 0.78152753],
       [0.34205829, 0.87600921, 0.85753156],
       [0.14256612, 0.13351367, 0.07859277],
       [0.78845681, 0.47217016, 0.79709931],
       [0.08045458, 0.73424546, 0.12805655],
       [0.66413662, 0.52027344, 0.22089005],
       [0.90519212, 0.80971351, 0.88855629],
       [0.08840759, 0.05134476, 0.23417102],
       [0.66582292, 0.54146893, 0.064408  ]])

In [8]:
a.shape

(10, 3)

In [9]:
len(a)

10

In [10]:
x=np.random.rand(20)
y=np.random.rand(20)

In [11]:
x

array([0.69402631, 0.78445777, 0.05773504, 0.98517944, 0.34895142,
       0.05966289, 0.17252887, 0.81463612, 0.74479224, 0.33501707,
       0.16724838, 0.59326226, 0.98282808, 0.13623985, 0.63818363,
       0.70489645, 0.09163426, 0.04265979, 0.60288014, 0.37869193])

In [12]:
y

array([0.06447798, 0.13556589, 0.53291432, 0.41844399, 0.35835668,
       0.30099591, 0.61924126, 0.93806224, 0.5690852 , 0.50539605,
       0.77123185, 0.95377623, 0.62475371, 0.00895493, 0.81723311,
       0.12093156, 0.7200192 , 0.59557824, 0.20518423, 0.2188121 ])

In [13]:
x*y

array([0.04474942, 0.10634571, 0.03076783, 0.41224242, 0.12504907,
       0.01795829, 0.106837  , 0.76417939, 0.42385024, 0.1693163 ,
       0.12898728, 0.56583944, 0.61402549, 0.00122002, 0.52154479,
       0.08524422, 0.06597842, 0.02540724, 0.1237015 , 0.08286238])

In [14]:
x/y

array([10.76377243,  5.78654253,  0.10833832,  2.35438781,  0.97375448,
        0.19821828,  0.27861333,  0.86842438,  1.30875347,  0.66288026,
        0.21685876,  0.62201409,  1.57314486, 15.21394143,  0.7809077 ,
        5.82888762,  0.12726641,  0.07162752,  2.93823819,  1.73067182])

### Pandas review

#### Working with data frames

In [15]:
import pandas as pd

In [16]:
d=pd.DataFrame(data=np.random.rand(100,3),columns=['A','B','C'])

In [17]:
d.head()

A         B         C
0  0.908584  0.273432  0.541305
1  0.743848  0.028351  0.830948
2  0.295735  0.415760  0.194624
3  0.484829  0.366845  0.287520
4  0.593594  0.661312  0.269906

In [18]:
d["A"]

0     0.908584
1     0.743848
2     0.295735
3     0.484829
4     0.593594
5     0.128708
6     0.122814
7     0.168878
8     0.594750
9     0.242133
10    0.115858
11    0.708346
12    0.552941
13    0.549309
14    0.127435
15    0.274983
16    0.691246
17    0.349943
18    0.105902
19    0.078394
20    0.020821
21    0.082561
22    0.676274
23    0.168378
24    0.716596
25    0.609002
26    0.918132
27    0.135590
28    0.713660
29    0.778926
        ...   
70    0.384597
71    0.078072
72    0.992091
73    0.722714
74    0.454508
75    0.595834
76    0.580741
77    0.429054
78    0.713832
79    0.842898
80    0.093821
81    0.547667
82    0.878420
83    0.807604
84    0.168572
85    0.991951
86    0.425371
87    0.337229
88    0.187687
89    0.426340
90    0.100159
91    0.261518
92    0.489770
93    0.166374
94    0.689027
95    0.920824
96    0.088374
97    0.028781
98    0.577502
99    0.075268
Name: A, Length: 100, dtype: float64

In [20]:
d.A

0     0.908584
1     0.743848
2     0.295735
3     0.484829
4     0.593594
5     0.128708
6     0.122814
7     0.168878
8     0.594750
9     0.242133
10    0.115858
11    0.708346
12    0.552941
13    0.549309
14    0.127435
15    0.274983
16    0.691246
17    0.349943
18    0.105902
19    0.078394
20    0.020821
21    0.082561
22    0.676274
23    0.168378
24    0.716596
25    0.609002
26    0.918132
27    0.135590
28    0.713660
29    0.778926
        ...   
70    0.384597
71    0.078072
72    0.992091
73    0.722714
74    0.454508
75    0.595834
76    0.580741
77    0.429054
78    0.713832
79    0.842898
80    0.093821
81    0.547667
82    0.878420
83    0.807604
84    0.168572
85    0.991951
86    0.425371
87    0.337229
88    0.187687
89    0.426340
90    0.100159
91    0.261518
92    0.489770
93    0.166374
94    0.689027
95    0.920824
96    0.088374
97    0.028781
98    0.577502
99    0.075268
Name: A, Length: 100, dtype: float64

In [19]:
d.shape

(100, 3)

### Loading data

In [21]:
d=pd.read_csv("train.csv")

In [23]:
d.head(20)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                               Rice, Master. Eugene    male   2.0      4   
17                       Williams, Mr. Charles Eugene    male   NaN      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                            Masselmani, Mrs. Fatima  female   NaN      0   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171   7.2500   NaN        S  
1       0          PC 17599  71.2833   C85        C  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
4       0            373450   8.0500   NaN        S  
5       0            330877   8.4583   NaN        Q  
6       0             17463  51.8625   E46        S  
7       1            349909  21.0750   NaN        S  
8       2            347742  11.1333   NaN        S  
9       0            237736  30.0708   NaN        C  
10      1           PP 9549  16.7000    G6        S  
11      0            113783  26.5500  C103        S  
12      0         A/5. 2151   8.0500   NaN        S  
13      5            347082  31.2750   NaN        S  
14      0            350406   7.8542   NaN        S  
15      0            248706  16.0000   NaN        S  
16      1            382652  29.1250   NaN        Q  
17      0            244373  13.0000   NaN        S  
18      0            345763  18.0000   NaN        S  
19      0              2649   7.2250   NaN        C

#### Q: how many passengers (data points or rows) do we have?

In [24]:
len(d)

891

#### General information about the dataset

In [25]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


#### Two ways to reference a column:

In [28]:
#d["Age"] and d.Age
d["Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
5       NaN
6      54.0
7       2.0
8      27.0
9      14.0
10      4.0
11     58.0
12     20.0
13     39.0
14     14.0
15     55.0
16      2.0
17      NaN
18     31.0
19      NaN
20     35.0
21     34.0
22     15.0
23     28.0
24      8.0
25     38.0
26      NaN
27     19.0
28      NaN
29      NaN
       ... 
861    21.0
862    48.0
863     NaN
864    24.0
865    42.0
866    27.0
867    31.0
868     NaN
869     4.0
870    26.0
871    47.0
872    33.0
873    47.0
874    28.0
875    15.0
876    20.0
877    19.0
878     NaN
879    56.0
880    25.0
881    33.0
882    22.0
883    28.0
884    25.0
885    39.0
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

#### Q: What's the mean age of passengers?

In [31]:
np.mean(d['Age'])

29.69911764705882

In [32]:
d.Age.mean()

29.69911764705882

#### Q: whats the mean price people paid?

In [33]:
d.Fare.mean()

32.204207968574636

#### Q: How many male/female passengers are there?

In [37]:
sum(d.Sex=='male')

577

In [38]:
sum(d.Sex=='female')

314

In [40]:
d.Sex.value_counts()

male      577
female    314
Name: Sex, dtype: int64

#### Q: find all values of Embarked and their counts?

In [42]:
d.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

#### How many passengers are in each class?

In [44]:
d.Pclass.value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

#### Quick summary of all numerical variables

In [45]:
d.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

#### Q: How many (unique) Passenger Classes 'Pclass' are there?

In [46]:
d.Pclass.value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

#### Q: How many passengers survived?

In [47]:
d.Survived.value_counts()

0    549
1    342
Name: Survived, dtype: int64

#### Q: How many females between 20 and 30?

In [51]:
d_F2030=d[(d.Sex == 'female') & (d.Age>=20) & (d.Age<=30)]

In [52]:
d_F2030.head()

PassengerId  Survived  Pclass  \
2             3         1       3   
8             9         1       3   
41           42         0       2   
53           54         1       2   
56           57         1       2   

                                                 Name     Sex   Age  SibSp  \
2                              Heikkinen, Miss. Laina  female  26.0      0   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
41  Turpin, Mrs. William John Robert (Dorothy Ann ...  female  27.0      1   
53  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female  29.0      1   
56                                  Rugg, Miss. Emily  female  21.0      0   

    Parch            Ticket     Fare Cabin Embarked  
2       0  STON/O2. 3101282   7.9250   NaN        S  
8       2            347742  11.1333   NaN        S  
41      0             11668  21.0000   NaN        S  
53      0              2926  26.0000   NaN        S  
56      0        C.A. 31026  10.5000   NaN        S

In [53]:
len(d_F2030)

83

#### Q: How many male passengers survived?

In [55]:
sum((d.Sex=='male') & (d.Survived==1))

109

#### Q: How many female passengers survived?

In [56]:
sum((d.Sex=='female') & (d.Survived==1))

233

#### Q: What percentage of male passengers survived?

In [58]:
sum((d.Sex=='male') & (d.Survived==1))/sum((d.Sex=='male'))*100

18.890814558058924

#### Q: What percentage of female passengers survived?

In [60]:
sum((d.Sex=='female') & (d.Survived==1))/sum((d.Sex=='female'))*100

74.20382165605095

#### Q: How much was the highest ticket price? and who paid it?

In [61]:
d.Fare.max()

512.3292

In [63]:
d.sort_values(by='Fare', ascending=False)

PassengerId  Survived  Pclass  \
258          259         1       1   
737          738         1       1   
679          680         1       1   
88            89         1       1   
27            28         0       1   
341          342         1       1   
438          439         0       1   
311          312         1       1   
742          743         1       1   
118          119         0       1   
299          300         1       1   
557          558         0       1   
700          701         1       1   
380          381         1       1   
716          717         1       1   
527          528         0       1   
377          378         0       1   
730          731         1       1   
779          780         1       1   
689          690         1       1   
318          319         1       1   
856          857         1       1   
268          269         1       1   
332          333         0       1   
609          610         1       1   
498          499         0       1   
305          306         1       1   
297          298         0       1   
708          709         1       1   
195          196         1       1   
..           ...       ...     ...   
363          364         0       3   
477          478         0       3   
129          130         0       3   
804          805         1       3   
825          826         0       3   
411          412         0       3   
654          655         0       3   
143          144         0       3   
202          203         0       3   
371          372         0       3   
818          819         0       3   
843          844         0       3   
326          327         0       3   
872          873         0       1   
378          379         0       3   
466          467         0       2   
597          598         0       3   
271          272         1       3   
277          278         0       2   
806          807         0       1   
481          482         0       2   
302          303         0       3   
179          180         0       3   
263          264         0       1   
815          816         0       1   
633          634         0       1   
413          414         0       2   
822          823         0       1   
732          733         0       2   
674          675         0       2   

                                                  Name     Sex    Age  SibSp  \
258                                   Ward, Miss. Anna  female  35.00      0   
737                             Lesurer, Mr. Gustave J    male  35.00      0   
679                 Cardeza, Mr. Thomas Drake Martinez    male  36.00      0   
88                          Fortune, Miss. Mabel Helen  female  23.00      3   
27                      Fortune, Mr. Charles Alexander    male  19.00      3   
341                     Fortune, Miss. Alice Elizabeth  female  24.00      3   
438                                  Fortune, Mr. Mark    male  64.00      1   
311                         Ryerson, Miss. Emily Borie  female  18.00      2   
742              Ryerson, Miss. Susan Parker "Suzette"  female  21.00      2   
118                           Baxter, Mr. Quigg Edmond    male  24.00      0   
299    Baxter, Mrs. James (Helene DeLaudeniere Chaput)  female  50.00      0   
557                                Robbins, Mr. Victor    male    NaN      0   
700  Astor, Mrs. John Jacob (Madeleine Talmadge Force)  female  18.00      1   
380                              Bidois, Miss. Rosalie  female  42.00      0   
716                      Endres, Miss. Caroline Louise  female  38.00      0   
527                                 Farthing, Mr. John    male    NaN      0   
377                          Widener, Mr. Harry Elkins    male  27.00      0   
730                      Allen, Miss. Elisabeth Walton  female  29.00      0   
779  Robert, Mrs. Edward Scott (Elisabeth Walton Mc...  female  43.00      0   
689                  Madill, Miss. Georgette Ale

#### Q: how many under age of 10? how many of them died?

In [67]:
len(d[d.Age < 10])

62

In [66]:
d[d.Age < 10].Survived.value_counts()

1    38
0    24
Name: Survived, dtype: int64

#### Q: how many first-class passengers died?

#### Q: what percentage of each class survived?

#### Q: what's the chance of survival for female, first-class passengers??

#### Q: what's the chance of survival for male, first-class passengers??

### Visualizations

In [ ]:
import numpy as np
from matplotlib import pyplot as plt

In [ ]:
%matplotlib inline 
#notebook

In [ ]:
a=np.random.randn(1000)

In [ ]:
b=np.random.randn(1000)

In [ ]:
plt.plot(a,':b')

In [ ]:
plt.hist(a, bins=50);

In [ ]:
plt.hist([a,b]);
plt.legend(["a","b"]);
plt.xlabel("counts");
plt.title("Test");

### Exploring data

#### Histrogram of Age

In [ ]:
d.hist("Age");

In [ ]:
plt.hist(d["Age"]);

#### Q: What is the distribution of Age in 'survided' vs 'not survived' groups?

In [ ]:
d.hist(column='Age',by='Survived');

#### Q: Can we put the two distributions (above) in the same graph?

In [ ]:
idx_died = d.Survived == 0
idx_survived = d.Survived == 1
age = d.Age.fillna(d.Age.mean())

In [ ]:
plt.hist([age[idx_died], age[idx_survived]], normed=True);
plt.legend(['died','survived']);

In [ ]:
plt.hist(d.Age.fillna(0));

#### Q: What is the distribution (histogram) of "Embarked"?

In [ ]:
d.Embarked.value_counts(dropna=False).plot.bar();

### Joining Tables

#### Let's say our data was given in two datasets:

In [ ]:
d=pd.read_csv("train.csv")
d1=d[["PassengerId","Name"]]
d2=d[["PassengerId","Age"]][d["Age"].notnull()].sort_values("Age").reset_index(drop=True)

In [ ]:
d1.head()

In [ ]:
len(d1)

In [ ]:
d2.head()

In [ ]:
len(d2)

In [ ]:
#merge is similar to SQL join
d3=d1.merge(d2,on="PassengerId")

In [ ]:
d3

### *Q: How many different passenger 'titles' (Mr. Miss. Dr. etc) are there? What is the distribution?

In [ ]:
d["title"]=

In [ ]:
title_counts = d.title.value_counts()

In [ ]:
title_counts

In [ ]:
title_counts.plot.bar(log=True, grid='on');